### ISSUE TITLE
Test the export command

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#71] opened 2015-03-13 10:27 UTC
The `export` command has to be tested too, of course. This will require some more work to ignore leading whitespace.

**Comment by jGleitz** [comment] 2015-03-13 10:35
Please note the different ways for a class to output when implementing this: [KIT-ILIAS: “Ausgabe von Zeilen”](https://ilias.studium.kit.edu/ilias.php?ref_id=413544&cmdClass=ilobjforumgui&thr_pk=53450&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI)

**Comment by jGleitz** [comment] 2015-03-13 14:28
Please note #74 when implementing this.

**Comment by jGleitz** [comment] 2015-03-13 20:50
Well be significantly easier with #81

**Comment by pcworld** [comment] 2015-03-14 06:51
Implemented in d09d998aa82cdea776e62e57f783f219dd919421 in #65

**Comment by RomanLangrehr** [comment] 2015-03-14 13:49
The dot export tests expects all names to be lower case - but I don't think they should be all lower case: The commands nodes and edges expect "Namen in Kleinschreibung" but the specification of the export command says "Produktknoten, ebenso wie Kategorieknoten, sollen durch deren Namen dargestellt werden." - So it should be case sensitive, I think.

**Comment by childen** [comment] 2015-03-14 14:08
The names are all lowercase in the example on the task sheet.

**Comment by jGleitz** [comment] 2015-03-14 14:08
There actually is nothing that forces them to be lowercase, that's correct.

But the example on the task sheet is all lower case, while the input file was not, so we propably should at least _allow_ all lower case output.

**Comment by RomanLangrehr** [comment] 2015-03-14 14:10
I'll post an ILIAS question on that...

**Comment by jGleitz** [comment] 2015-03-14 14:11
> I'll post an ILIAS question on that...

That's surely the best way to go.

**Comment by pcworld** [comment] 2015-03-14 14:17
> So it should be case sensitive, I think

The issue is, there is no real "case sensitive" version of a name, since the input file can contain all kinds of variations of capitalization. That's why I think outputting them lower-case makes most sense.

**Comment by jGleitz** [comment] 2015-03-14 14:36
We'll have to rely on a official statement. I can only hope they'll answer the questions that are still open soon.

**Comment by pcworld** [comment] 2015-03-15 18:45
I interpret the [official statement](https://ilias.studium.kit.edu//ilias.php?ref_id=413544&cmdClass=ilobjforumgui&thr_pk=53477&pos_pk=196624&offset=0&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI#196624) that our current tests are valid.
Closing this. If you think my interpretation is wrong, feel free to comment.

**Closed as completed by pcworld** 2015-03-15 18:45 UTC
Labels: Test, TODO
