### ISSUE TITLE
Speedup +12

### ISSUE THREAD

**Issue by kelunik** [jGleitz/JUnit-KIT#171] opened 2015-03-28 09:54 UTC
https://github.com/jGleitz/JUnit-KIT/blob/ant-development/src/final2/subtests/InvalidCommandLineArgumentsTest.java#L130

I think that's not something that should error. `+12` is a valid integer.

**Comment by pcworld** [comment] 2015-03-28 11:05
Duplicate of #164

**Closed as completed by pcworld** 2015-03-28 11:05 UTC
Labels: duplicate
